---
- hosts: '{{ target }}'
  name: Configure and install software on the server
  become: yes
  vars:

    - rpm_dest: /tmp/agent.bin
    - rpm_src: RPM/agent.bin
    - inst_cmd: /tmp/agent.bin --eula accept --silent --server-host aserver.domain.lan --server-port 9898 --passphrase tripwireprod


  tasks:

    - name: check and see if is installed
      stat:
        path: /usr/local/tripwire/te/agent/jre/bin/java
      register: tw_inst

    - name: copy and install BIN file to the server
      copy:
        src: '{{ rpm_src }}'
        dest: '{{ rpm_dest }}'
        mode: 0755
      when: tw_inst.stat.exists == False

    - name: install agent that was previously copied
      command: '{{ inst_cmd }}'
      when: tw_inst.stat.exists == False
      notify: start agent

  handlers:
    - name: start agent
      service:
        name: agendaemon
        state: started

